output:
  formats:
    - format: colored-line-number
  sort-results: true

linters:
  enable-all: true
  disable:
    # - exhaustruct
    # - godox
    - gomnd
    - stylecheck
    - varnamelen

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: io/ioutil
            desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil
        allow:
          - $gostd
          - golang.org/x/net/http/httpguts
          - github.com/eser/go-service
          - go.uber.org/fx
          - github.com/oklog/ulid/v2
          - github.com/go-playground/validator/v10
          - github.com/stretchr/testify
          - github.com/go-faker/faker/v4
          - github.com/getkin/kin-openapi/openapi3
  revive:
    rules:
      - name: var-naming
        disabled: true
        arguments: []

issues:
  fix: true
  exclude-dirs:
    - docs
